version: "3.9"

services:
  api:
    build:
      context: ../backend/BarCodeAPI/BarCodeAPI
      dockerfile: Dockerfile
    container_name: barcode_api
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
    depends_on:
      - database
    networks:
      - barcode_net

  migrate-add:
    image: mcr.microsoft.com/dotnet/sdk:9.0
    env_file:
      - .env
    environment:
      - DB_CONNECTION=${DB_CONNECTION}
    volumes:
      - ../:/src
      - ./migrate.sh:/src/migrate.sh:ro
    working_dir: /src
    entrypoint: ["sh", "migrate.sh", "add"]
    depends_on:
      - database
    networks:
      - barcode_net

  migrate-update:
    image: mcr.microsoft.com/dotnet/sdk:9.0
    env_file:
      - .env
    volumes:
      - ../:/src
      - ./migrate.sh:/src/migrate.sh:ro
    working_dir: /src
    entrypoint: ["sh", "migrate.sh", "update"]
    depends_on:
      - database
    networks:
      - barcode_net

  database:
    image: mysql:8.0
    container_name: barcode_db
    restart: always
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - barcode_net
  
  populadbworker:
    build:
      context: ../backend/PopulaDbWorker/PopulaDbWorker
      dockerfile: Dockerfile
    container_name: populadbworker
    env_file:
      - .env
    depends_on:
      - database
    networks:
      - barcode_net

networks:
  barcode_net:

volumes:
  db_data:
