version: "3.9"

services:
  api:
    build:
      context: ../
      dockerfile: backend/BarCodeAPI/BarCodeAPI/Dockerfile
    container_name: barcode_api
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
    depends_on:
      - database
    networks:
      - barcode_net

  database:
    image: mysql:8.0
    container_name: barcode_db
    restart: always
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - barcode_net

networks:
  barcode_net:

volumes:
  db_data:
